Repository Team-Bloblow/Bloblow-Server, pull requests merged in 2024-12, with the labels that each got.

#62 Remove: View 관련 파일 및 로직 삭제
  bin/www
  public/stylesheets/style.css
  routes/indexRoute.js
  server.js
  views/error.pug
  views/index.pug
  views/layout.pug
Labels: remove

#66 Feat: 키워드에 대한 게시물 수동 크롤링 로직 구현
  controllers/keywordsController.js
  routes/keywordsRoute.js
Labels: ✨ feat

#68 Feat: 최근 업데이트 그룹의 키워드별 게시물 수 조회 API 구현
  controllers/groupsController.js
  routes/groupsRoute.js
Labels: ✨ feat, 📣 code review

#70 Feat: 신규 사용자에게 샘플 그룹 데이터 추가해주는 로직 추가
  config/constants.js
  controllers/userController.js
Labels: ✨ feat

#72 Fix: 크롤링 기준 관련하여 date 로직 수정 및 서버 상태 체크를 위한 indexRoute 복구
  bin/www
  public/stylesheets/style.css
  routes/indexRoute.js
  server.js
  utils/date.js
  views/error.pug
  views/index.pug
  views/layout.pug
Labels: ✏ fix

#74 Feat: 기존 그룹 및 키워드 생성하는 API를 각 그룹과 키워드를 생성하는 API로 분리
  controllers/groupController.js
  controllers/keywordController.js
  routes/groupRoute.js
Labels: ✏ fix

#76 Fix: 키워드 대시보드 내의 날짜 관련 이슈 수정
  services/crawling.js
  utils/date.js
Labels: ✏ fix

#80 Fix: 샘플 데이터 추가하는 로직 및 키워드 정보 조회에서 게시물 ID 목록 조회하는 로직 삭제
  config/constants.js
  controllers/keywordsController.js
  controllers/userController.js
Labels: ✏ fix

#82 Feat: 특정 groupId에 대한 그룹 데이터 fetch 로직 구현
  controllers/groupController.js
  routes/groupRoute.js
Labels: ✨ feat, 📣 code review
