Repository Team-Bloblow/Bloblow-Server, pull requests merged in 2024-11, with the labels that each got.

#4 Feat: 보일러 플레이트 세팅
  .github/ISSUE_TEMPLATE/feature.yml
  .github/pull_request_template.md
  .gitignore
  .husky/pre-commit
  .prettierignore
  .prettierrc
  app.js
  bin/www
  eslint.config.mjs
  package-lock.json
  package.json
  public/stylesheets/style.css
  routes/index.js
  routes/users.js
Labels: ⚙ chore, ✨ feat, 📃 docs

#5 Feat: 블로그 게시물 크롤링 로직 구현
  config/constants.js
  controllers/postController.js
  models/postModel.js
  package-lock.json
  package.json
  services/crawling.js
  utils/date.js
  utils/validation.js
Labels: ⚙ chore, ✨ feat, 📣 code review

#6 Feat: 키워드 생성 API
  app.js
  controllers/keywordController.js
  models/groupModel.js
  models/keywordModel.js
  routes/index.js
  routes/indexRoute.js
  routes/keywordRoute.js
Labels: ✨ feat, 📣 code review

#8 Feat: 키워드 생성 후 게시물 크롤링 작업 추가
  app.js
  controllers/keywordController.js
  controllers/postController.js
  models/groupModel.js
  models/postModel.js
  package-lock.json
  package.json
  services/crawling.js
  utils/validation.js
Labels: ⚙ chore, ✏ fix, ✨ feat, 📣 code review

#12 Feat: 가입/로그인시 사용자 정보 DB 등록/업데이트 기능 구현
  app.js
  controllers/keywordController.js
  controllers/userController.js
  models/userModel.js
  routes/userRoute.js
Labels: ✨ feat, 📣 code review

#13 Feat: 블로그 게시물 목록 조회 API
  app.js
  controllers/keywordController.js
  controllers/postController.js
  routes/postRoute.js
  utils/validation.js
Labels: ✨ feat, 📣 code review

#14 Fix: Validation 함수명 수정 적용
  controllers/userController.js
Labels: ✏ fix

#16 Fix: 클라이언트에서 새로 그룹 생성 시 InvalidGroupId 에러 나는 문제 해결
  controllers/keywordController.js
Labels: ✏ fix, 🐛 bug

#21 Feat: 키워드 상세 조회 API 구현
  app.js
  controllers/groupsController.js
  controllers/keywordsController.js
  routes/keywordsRoute.js
Labels: ✏ fix, ✨ feat

#24 Feat: 광고 블로그 필터링 로직 구현
  controllers/postController.js
  services/crawling.js
  utils/sanitizeHtmlEntity.js
  utils/validation.js
Labels: ✨ feat, 📣 code review

#28 Feat: 키워드 대시보드 내 오늘의 게시물 수, 주간 게시물 수 조회 API
  config/constants.js
  controllers/postController.js
  routes/postRoute.js
  utils/date.js
Labels: ✨ feat, 📣 code review

#31 Fix: 키워드 대시보드의 차트 API 주소 수정 및 cursorId을 토요일로 설정 변경
  controllers/postController.js
  routes/postRoute.js
  utils/date.js
Labels: ✏ fix

#35 Feat: 포함/제외 키워드 필터링 API
  controllers/postController.js
  models/keywordModel.js
Labels: ✨ feat, 📣 code review

#36 Feat: 키워드 대시보드 내 좋아요 수, 댓글 수 차트 조회 API
  controllers/postController.js
  routes/postRoute.js
Labels: ✏ fix, ✨ feat, 📣 code review

#32 Feat: 그룹 대시보드 내 모든 키워드에 대해서 주간 게시물 수, 좋아요 수, 댓글 수 조회 API
  .github/pull_request_template.md
  controllers/postController.js
  routes/postRoute.js
  utils/date.js
Labels: ✨ feat, 📣 code review

#46 Feat: 키워드 대시보드 내 차트 API에 대한 기간 설정 파라미터 추가 및 광고 여부, 반응 수 차트 API 추가
  config/constants.js
  controllers/postController.js
  routes/postRoute.js
  utils/date.js
Labels: ✨ feat, 📣 code review, 🔨 refactor

#50 Feat: 게시물 정렬 및 광고 필터링 기능 구현
  controllers/postController.js
Labels: ✨ feat, 📣 code review

#51 Fix: 백엔드 일반 서버 및 크롤링 서버 배포 시 문제 해결
  .platform/nginx/conf.d/proxy.conf
  bin/www
  config/constants.js
  package-lock.json
  package.json
  server.js
  services/crawling.js
  utils/fetchHandler.js
  utils/sanitizeHtmlEntity.js
Labels: ✏ fix, ✨ feat, 📣 code review, 🔨 refactor

#54 Feat: 그룹 이름 변경 API 구현
  controllers/groupController.js
  routes/groupRoute.js
  server.js
Labels: ✨ feat

#60 Fix: 그룹 정보 내에서도 삭제하려는 키워드 정보 삭제하는 로직 추가
  controllers/keywordController.js
Labels: ✏ fix
